### ISSUE TITLE
Autoprefixer 5.2.0 API change

### ISSUE THREAD

**Issue by hacfi** [less/less-plugin-autoprefix#13]
With the release of [Autoprefixer 5.2.0](https://github.com/postcss/autoprefixer/releases) you get the following warning:
```
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
```

https://github.com/postcss/autoprefixer-core/commit/d35c9321e2ca956fafc82e443e3b2cd06c21aaab

Not sure how to fix this so didn’t create a PR myself.

**Comment by giggio** [comment]
I am receiving the same warning. Is there a workaround at this time?

**Comment by lukeapage** [comment]
new version is published now.

**Comment by hacfi** [comment]
@lukeapage Thanks for taking care of this so quickly!

**Comment by hacfi** [comment]
Works like a charm @lukeapage :)
