### ISSUE TITLE
ENONET  Error

### ISSUE THREAD

**Issue by LukeMauldin** [less/less-plugin-autoprefix#17]
Receive error:
```
lmauldin@9c68fd81e7d7:/var/www/html/pmtool/erp-extender/pms420$ ./node_modules/.bin/gulp less
[15:24:43] Using gulpfile /var/www/html/pmtool/erp-extender/pms420/gulpfile.js
[15:24:43] Starting 'less'...
Potentially unhandled rejection [2] Error: ENOENT, open '<input css 1>'
    at Error (native)
```
Relevant gulp file:
```
gulp.task("less", function() {
    var cleancss = new lessPluginCleanCSS({ advanced: true });
   var autoprefix= new lessPluginAutoPrefix({browsers: ["last 2 versions"]});
    //return gulp.src(['./assets/styles/application.less', './assets/styles/*/*.less'])
    return gulp.src(['./assets/styles/application.less'])
        .pipe(sourcemaps.init())
        .pipe(less({
            plugins: [autoprefix]
        }))
        .pipe(sourcemaps.write()) //.pipe(sourcemaps.write('./maps'))
        .pipe(gulp.dest('./webroot/styles'));
});
```

**Comment by seven-phases-max** [comment]
It looks like the same issue as in https://github.com/less/less-plugin-clean-css/issues/8, though I have no idea of it could be too. It looks like some incompatibility between how `gulp-less` and `gulp-sourcemaps` handle their sourcemaps (at least when Less plugins are used).

**Comment by LukeMauldin** [comment]
I disabled sourcemaps and now the plugin runs without error.  However, I don't see any prefixed CSS files?
```
gulp.task("styles", function() {
    var cleancss = new lessPluginCleanCSS({ advanced: true });
    var autoprefix= new lessPluginAutoPrefix({browsers: ["last 2 versions"]});
    return gulp.src(['./assets/styles/application.less', './assets/styles/*/*.less'])
        .pipe(changed('./webroot/styles'))
        //.pipe(sourcemaps.init())
        .pipe(less({
            plugins: [autoprefix]
        }))
        //.pipe(sourcemaps.write()) //.pipe(sourcemaps.write('./maps'))
        .pipe(gulp.dest('./webroot/styles'));
});
```

**Comment by seven-phases-max** [comment]
>However, I don't see any prefixed CSS files?

Are you sure? Most of "last 2 browsers" versions may not need prefixes for most of properties, but nothing at all... hmm, try "last 99 browsers" just to make sure it's actually working.

**Comment by LukeMauldin** [comment]
I have updated my gulp file to the below and still don't see any prefixed CSS files in the output.

```
gulp.task("styles", function() {
    var cleancss = new lessPluginCleanCSS({ advanced: true });
    var autoprefix= new lessPluginAutoPrefix({browsers: ["last 2 versions"]});
    return gulp.src(['./assets/styles/application.less', './assets/styles/*/*.less'])
        .pipe(changed('./webroot/styles'))
        //.pipe(sourcemaps.init())
        .pipe(less({
            plugins: [autoprefix]
        }))
        //.pipe(sourcemaps.write()) //.pipe(sourcemaps.write('./maps'))
        .pipe(gulp.dest('./webroot/styles'));
});
```

**Comment by jbhannah** [comment]
I get this issue (`Potentially unhandled rejection [2] Error: ENOENT: no such file or directory, open '$stdin'`) specifically when using this plugin in combination with sourcemaps. When using just the clean-css LESS plugin, I get correct source maps.

```js
gulp.task('less', function () {
  return gulp.src(['./assets/css/main.less'], {base: '.'})
    .pipe(gulpIf(!isProd(), sourcemaps.init()))
    .pipe(less({
      plugins: [cleanCSS] // works
   // plugins: [autoprefix, cleanCSS] // doesn't work
    }))
    .pipe(gulpIf(!isProd(), sourcemaps.write('.')))
    .pipe(gulp.dest(DEST))
    .pipe(livereload());
});
```

**Comment by jbhannah** [comment]
It should be noted that this is on io.js 3.0.x and 3.1.x. Could be an io.js issue?

**Comment by borekb** [comment]
Confirming this issue on Node 4.0.0.

**Comment by lukeapage** [comment]
My current thinking is that this is not node version specific and is the same bug that @seven-phases-max pointed to, which is a bug in clean-css. https://github.com/less/less-plugin-clean-css/issues/8.. which is https://github.com/jakubpawlowicz/clean-css/issues/593

If you can reproduce without clean-css, I'll investigate.

If you are stuck on this bug consider helping to track down the problem in clean css (some progress and evidence is on that issue) or find a different css minifier (or don't use sourcemaps).

**Comment by borekb** [comment]
I'd like to help with this but am not very well-versed in the less package / its plugins. This is what my code roughly looks like:

    var less = require('gulp-less');
    var sourcemaps = require('gulp-sourcemaps');
    var autoprefixer = require('less-plugin-autoprefix');

    gulp.task('less', function () {

        var destFolder = projectDir + '/css';

        return gulp.src(projectDir + '/css/style-*.less')
            .pipe(sourcemaps.init())
            .pipe(less({
                plugins: [new autoprefixer()],
                relativeUrls: true
            }))
            .on('error', function (error) {
                console.log(error);
            })
            .pipe(sourcemaps.write('.'))
            .pipe(gulp.dest(destFolder));

    });

What do you mean by "reproducing without clean-css"?

**Comment by lukeapage** [comment]
> What do you mean by "reproducing without clean-css"?

okay so it isn't a clean-css issue, since you are reproducing with the above code.

is that in a repo somewhere? if I have an easy to reproduce test case it makes tracking it down easier

**Comment by borekb** [comment]
There isn't but I'll try to create one.

**Comment by borekb** [comment]
There you go: https://github.com/borekb/less-plugin-autoprefix-17

**Comment by lukeapage** [comment]
thanks, I'll take a look now

**Comment by lukeapage** [comment]
seems like it might be a regression in postcss, but am investigating further
https://github.com/postcss/postcss/issues/96

the sourcemap going into postcss has all less sources. coming out it has 1 more source, named `<input css 1>` which doesn't exist (of course).

**Comment by lukeapage** [comment]
Ok, it might not be a regression, but it is related to a quirk in postcss.

one way to fix it is to set
```
            sourceMap: {
                outputSourceFiles: true
            },
```

in gulp less.

basically postcss always adds its input to the sources. If you have an output filename its possible to get postcss to merge that source with the existing one (I don't really know why its like that). postcss source is less' output and actually isn't referenced by the map, because the map needs to go from the input less files straight to the output.

possible solutions
1. get postcss to fix this (I tried previously and wasn't listened to)
2. remove the postcss source from the sourcemap after it is returned
3. include the postcss source in the sources content, so nothing tries to fetch it

**Comment by lukeapage** [comment]
Please try again now, I found a simpler solution.
It is published as 1.5.1

**Comment by jbhannah** [comment]
:+1:, fixed it for me.

**Comment by borekb** [comment]
Yep, worked for me too. Thanks!

**Comment by wazp** [comment]
For some reason this still doesn't work for me with 1.5.1. I have version 5.0.10 of postcss installed - maybe some more changes were made that broke it again?

A real shame that postcss developers aren't listening to you at all!

**Comment by lukeapage** [comment]
@wazp I've re-installed @borekb example repo with the latest versions and re-ran the test case and it still passes.
Could you provide a test case?

**Comment by wolfy1339** [comment]
The workarounds noted above don't seem to work for me either

**Comment by matthew-dean** [comment]
@wolfy1339 Would this be a suitable workaround? https://github.com/Crunch/postcss-less

**Comment by wolfy1339** [comment]
I will take a look, but in the mean time I can suggest another workaround, instead of using LESS plugins we use gulp or grunt plugins instead. For some reason that fixes the sourcemap problem



On Mon, May 16, 2016 at 8:07 PM -0700, "Matthew Dean" <notifications@github.com<mailto:notifications@github.com>> wrote:


@wolfy1339<https://github.com/wolfy1339> Would this be a suitable workaround? https://github.com/Crunch/postcss-less

-

**Comment by cybersam** [comment]
Can someone with edit access please correct the title of this issue by replacing "ENONET" with "ENOENT"? This will save some time for people (like me) searching online for "ENONET"; this issue is the first one shown by Google.
