### ISSUE TITLE
Deps Update?

### ISSUE THREAD

**Issue by Ashwell** [less/less-plugin-autoprefix#18]
Has anyone tried this plugin with updated versions of postCSS and autoprefixer?

Looks like it might also require switching from [autoprefixer-core](https://www.npmjs.com/package/autoprefixer-core) to [autoprefixer](https://www.npmjs.com/package/autoprefixer)

**Comment by tobiastom** [comment]
+1

**Comment by lukeapage** [comment]
thanks, merged and published

**Comment by tobiastom** [comment]
Works great. Thanks!
