### ISSUE TITLE
>> Local Npm module "less-plugin-autoprefix" not found. Is it installed?

### ISSUE THREAD

**Issue by rasmuseeg** [less/less-plugin-autoprefix#21]
I always get this error.

I've installed using: `npm install less-plugin-autoprefix --save-dev`

Any suggestions?

**Comment by lukeapage** [comment]
sorry, looks to me like npm didn't install or something went wrong.. 

what gives the local Npm module not found message?

**Comment by rasmuseeg** [comment]
Found that removing the grunt.loadNpmTasks('less-plugin-autoprefix'); resolved this issue.
