### ISSUE TITLE
Doesn't work with imported files

### ISSUE THREAD

**Issue by waterplea** [less/less-plugin-autoprefix#23]
Hello.

I use style.less file to aggregate a lot of different less files inside my project. And I've configured grunt to do it this way using grunt-contrib-less:
```js
less: {
            style: {
                options: {
                    relativeUrls: true,
                    plugins: [
                        new (require('less-plugin-autoprefix'))({browsers: ["last 2 Chrome versions"]})
                    ],
                    paths: ['src/main/webapp/assets/styles'],
                },
                files: {
                    'src/main/webapp/assets/styles/style.css': 'src/main/webapp/assets/styles/style.less'
                }
            }
        },
```
However only the code that is inside style.less gets prefixed, not the imported less files. Could you advice please, how do I get this to work properly? Do I have to use postcss on the compiled css instead?

**Comment by seven-phases-max** [comment]
>However only the code that is inside style.less gets prefixed, not the imported less files.

I don't thing this is actually possible at all (there's no separate compilation/prefixing step for imported files, everything is compiled somewhat like one large string instead). You need to provide more details. example of the imported code which is not prefixed etc.).

**Comment by waterplea** [comment]
There is not much to provide, basically, my style.less looks like a bunch of these lines:

@import "../../app/components/component-name/styles/component-name.less";

And if I use less-plugin-autoprefix with my grunt compilation I get it all untouched. If I add, on the other hand, something like this at the end of style.less:

.stuff {
    user-select: none;
}

I get that prefixed properly.

**Comment by seven-phases-max** [comment]
Did you test `user-select` in either of your imported files?

**Comment by waterplea** [comment]
Yes, it didn't get prefixed in the imported files. I'll try to reproduce the issue in a minimal setup and will post back with the results. What you say seems reasonable, I'm sure I will find the issue while minimizing the environment.

**Comment by waterplea** [comment]
Sorry for the false alarm, my IDE's file watchers were messing with LESS compilation.
