### ISSUE TITLE
BrowserslistError: Unknown browser query `browsers`

### ISSUE THREAD

**Issue by IonicaBizau** [less/less-plugin-autoprefix#26]
The example simply fails with this error:

```sh
BrowserslistError: Unknown browser query `browsers`
```

Is this a known issue?

**Comment by selbekk** [comment]
"browsers" in the example is a list of browsers, not the word "browsers". [Here's the relevant explanation in the Autoprefixer docs](https://github.com/postcss/autoprefixer).

**Comment by IonicaBizau** [comment]
Ah, now I see that row explaining what `browsers` is. Thanks! :+1:
