### ISSUE TITLE
Unable to load plugin autoprefix

### ISSUE THREAD

**Issue by cbou** [less/less-plugin-autoprefix#30]
```
$ npm install -g less                  
~/.nvm/v8.9.4/bin/lessc -> ~/.nvm/v8.9.4/lib/node_modules/less/bin/lessc
+ less@3.0.1
added 66 packages in 3.988s

$ npm install -g less-plugin-autoprefix
+ less-plugin-autoprefix@1.5.1
added 20 packages in 2.296s

$ lessc styles.less --autoprefix="browsers" 
Unable to load plugin autoprefix please make sure that it is installed under or at the same level as less
```

Any idea?

**Comment by iamhefang** [comment]
我也是更新了less以后加载不了插件了

**Comment by cinques** [comment]
For less-plugin-autoprefix **v1.5.1** need less **v2.7.3**
I hope that authors will release new version of less-plugin-autoprefix for less 3.x

**Comment by calvinjuarez** [comment]
A new version is coming to NPM.  Less 3.x also had an issue loading some plugins for a bit.  Update Less to 3.7 and you should see it fixed.

**Comment by calvinjuarez** [comment]
@cbou, @cinques: I released v2 to npm.  Please update both this plugin and Less to their latest releases and let me know if your issues persist.  For now, I'm closing this issue until I hear back.
