### ISSUE TITLE
Potentially unhandled rejection [2] Error: ENOENT

### ISSUE THREAD

**Issue by stebru** [less/less-plugin-autoprefix#7]
I set up a repo that reproduces the issue here: https://github.com/stebru/gulp-less-test

**Comment by bassjobsen** [comment]
I wrote a PR which fixes this issue (see: https://github.com/less/less-plugin-autoprefix/pull/8).

What happens? when you are using gulp-sourcemap `file.sourceMap` will be set. [gulp-less now calls less with the `souremap` option set to `true`](https://github.com/plus3network/gulp-less/blob/master/index.js#L36). Less does not use inline sourcemaps by default, so when `sourcemaps=true` and `sourceMapFileInline` is not set, Less expects an output file to write the sourcemap to. In the gulp environment there is not such a output file set. Less does not throw an error when the output file is missing but sets `sourceMapURL` to `undefined`.

**Comment by bassjobsen** [comment]
as far as i understand this issue is due to https://github.com/less/less.js/issues/2413
