### ISSUE TITLE
autoprefixer-core dependency

### ISSUE THREAD

**Issue by Sergey-Nosov-GH** [less/less-plugin-autoprefix#9]
Hi,

Thank you for making the plugin. 

I was wondering if there is a specific reason to have the dependency on the version _5.0_ of __autoprefixer-core__? The current branch is _5.1_.

Thanks again.

**Comment by seven-phases-max** [comment]
They just update it almost every week. This plugin is not updated so often.

**Comment by Sergey-Nosov-GH** [comment]
Would it be safe to change
```"autoprefixer-core": "~5.0.0"```
to
```"autoprefixer-core": "^5.0.0"```
then?

We want those fixes they are making in the core package.

Thank you.

**Comment by seven-phases-max** [comment]
I guess it would (in the changelog I can't see anything breaking). But you never know until you actually change it and test :).

**Comment by Sergey-Nosov-GH** [comment]
Good idea. Seems to work fine. Pull request created.
Thank you.
